apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastdb-dp1-kafka-data-20250721
  namespace: fastdb-dp1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
