import pytest

from db import DiaSource

from basetest import BaseTestDB


class TestDiaSource( BaseTestDB ):

    @pytest.fixture
    def basetest_setup( self, obj1 ):
        self.cls = DiaSource
        self.columns = {
            'base_procver_id',
            'diaobjectid',
            'visit',
            'ssobjectid',
            'detector',
            'x',
            'y',
            'xerr',
            'yerr',
            'x_y_cov',
            'band',
            'midpointmjdtai',
            'ra',
            'raerr',
            'dec',
            'decerr',
            'ra_dec_cov',
            'psfflux',
            'psffluxerr',
            'psfra',
            'psfraerr',
            'psfdec',
            'psfdecerr',
            'psfra_psfdec_cov',
            'psfflux_psfra_cov',
            'psfflux_psfdec_cov',
            'psflnl',
            'psfchi2',
            'psfndata',
            'snr',
            'scienceflux',
            'sciencefluxerr',
            'fpbkgd',
            'fpbkgderr',
            'extendedness',
            'reliability',
            'ixx',
            'ixxerr',
            'iyy',
            'iyyerr',
            'ixy',
            'ixyerr',
            'ixx_ixy_cov',
            'ixx_iyy_cov',
            'iyy_ixy_cov',
            'ixxpsf',
            'iyypsf',
            'ixypsf',
            'flags',
            'pixelflags',
        }
        self.safe_to_modify = [
            'detector',
            'x',
            'y',
            'xerr',
            'yerr',
            'x_y_cov',
            'band',
            'midpointmjdtai',
            'ra',
            'raerr',
            'dec',
            'decerr',
            'ra_dec_cov',
            'psfflux',
            'psffluxerr',
            'psfra',
            'psfraerr',
            'psfdec',
            'psfdecerr',
            'psfra_psfdec_cov',
            'psfflux_psfra_cov',
            'psfflux_psfdec_cov',
            'psflnl',
            'psfchi2',
            'psfndata',
            'snr',
            'scienceflux',
            'sciencefluxerr',
            'fpbkgd',
            'fpbkgderr',
            'extendedness',
            'reliability',
            'ixx',
            'ixxerr',
            'iyy',
            'iyyerr',
            'ixy',
            'ixyerr',
            'ixx_ixy_cov',
            'ixx_iyy_cov',
            'iyy_ixy_cov',
            'ixxpsf',
            'iyypsf',
            'ixypsf',
            'flags',
            'pixelflags',
        ]
        self.uniques = []

        self.obj1 = DiaSource( base_procver_id=obj1.base_procver_id,
                               diaobjectid=obj1.diaobjectid,
                               visit=1,
                               detector=1,
                               band='r',
                               midpointmjdtai=60000.,
                               ra=42.0001,
                               dec=12.9998,
                               psfflux=123.4,
                               psffluxerr=5.6,
                              )
        self.dict1 = { k: getattr( self.obj1, k ) for k in self.columns }
        self.obj2 = DiaSource( base_procver_id=obj1.base_procver_id,
                               diaobjectid=obj1.diaobjectid,
                               visit=2,
                               detector=2,
                               band='i',
                               midpointmjdtai=60010.,
                               ra=42.0002,
                               dec=13.0001,
                               psfflux=124.6,
                               psffluxerr=8.0
                              )
        self.dict2 = { k: getattr( self.obj2, k ) for k in self.columns }
        self.dict3 = { 'base_procver_id': obj1.base_procver_id,
                       'diaobjectid': obj1.diaobjectid,
                       'visit': 3,
                       'detector': 3,
                       'band': 'g',
                       'midpointmjdtai': 60015.,
                       'ra': 41.9999,
                       'dec': 13.0002,
                       'psfflux': 135.7,
                       'psffluxerr': 9.1 }
