import pytest

from db import DiaSource

from basetest import BaseTestDB


class TestDiaSource( BaseTestDB ):

    @pytest.fixture
    def basetest_setup( self, obj1 ):
        self.cls = DiaSource
        self.columns = {
            "base_procver_id",
            "diaobjectid",
            "visit",
            "diasourceid",
            "detector",
            "band",
            "midpointmjdtai",
            "ra",
            "dec",
            "psfflux",
            "psffluxerr",
            "apflux",
            "apfluxerr",
            "bboxsize",
            "decerr",
            "extendedness",
            "flags",
            "ixx",
            "ixxpsf",
            "ixy",
            "ixypsf",
            "iyy",
            "iyypsf",
            "parentdiasourceid",
            "pixelflags",
            "psfchi2",
            "psflnl",
            "psfndata",
            "ra_dec_cov",
            "raerr",
            "reliability",
            "scienceflux",
            "sciencefluxerr",
            "snr",
            "ssobjectid",
            "templateflux",
            "templatefluxerr",
            "timeprocessedmjdtai",
            "timewithdrawnmjdtai",
            "x",
            "x_y_cov",
            "xerr",
            "y",
            "yerr",
        }
        self.safe_to_modify = [
            "detector",
            "band",
            "midpointmjdtai",
            "ra",
            "dec",
            "psfflux",
            "psffluxerr",
            "apflux",
            "apfluxerr",
            "bboxsize",
            "decerr",
            "extendedness",
            "flags",
            "ixx",
            "ixxpsf",
            "ixy",
            "ixypsf",
            "iyy",
            "iyypsf",
            "parentdiasourceid",
            "pixelflags",
            "psfchi2",
            "psflnl",
            "psfndata",
            "ra_dec_cov",
            "raerr",
            "reliability",
            "scienceflux",
            "sciencefluxerr",
            "snr",
            "ssobjectid",
            "templateflux",
            "templatefluxerr",
            "timeprocessedmjdtai",
            "timewithdrawnmjdtai",
            "x",
            "x_y_cov",
            "xerr",
            "y",
            "yerr",
        ]
        self.uniques = []

        self.obj1 = DiaSource( base_procver_id=obj1.base_procver_id,
                               diaobjectid=obj1.diaobjectid,
                               diasourceid=1,
                               visit=1,
                               detector=1,
                               band='r',
                               midpointmjdtai=60000.,
                               ra=42.0001,
                               dec=12.9998,
                               psfflux=123.4,
                               psffluxerr=5.6,
                               x=128,
                               y=128,
                               pixelflags=0,
                               flags=0
                              )
        self.dict1 = { k: getattr( self.obj1, k ) for k in self.columns }
        self.obj2 = DiaSource( base_procver_id=obj1.base_procver_id,
                               diaobjectid=obj1.diaobjectid,
                               diasourceid=2,
                               visit=2,
                               detector=2,
                               band='i',
                               midpointmjdtai=60010.,
                               ra=42.0002,
                               dec=13.0001,
                               psfflux=124.6,
                               psffluxerr=8.0,
                               x=131.5,
                               y=131.5,
                               pixelflags=0,
                               flags=0
                              )
        self.dict2 = { k: getattr( self.obj2, k ) for k in self.columns }
        self.dict3 = { 'base_procver_id': obj1.base_procver_id,
                       'diaobjectid': obj1.diaobjectid,
                       'diasourceid': 3,
                       'visit': 3,
                       'detector': 3,
                       'band': 'g',
                       'midpointmjdtai': 60015.,
                       'ra': 41.9999,
                       'dec': 13.0002,
                       'psfflux': 135.7,
                       'psffluxerr': 9.1,
                       'x': 148.7,
                       'y': 148.7 }
