"""
Integration test for WAL archiving via pgBackRest to S3-compatible object stores.

Phase 2.3 deliverable: Verify that when archiving is enabled on the primary,
WAL segments are archived to both MinIO object stores after database writes.

This test uses the existing snana_fits_maintables_loaded_module fixture which
loads real ELAsTiCC2 FITS data via FITSLoader (5 parallel processes), producing
~346 DiaObjects, ~1,862 DiaSources, ~52,172 DiaForcedSources, and ~356 host
galaxies.  That volume of bulk inserts generates substantial WAL — enough to
confirm archiving works under realistic write loads.

Requirements:
    - Docker Compose environment running (postgres, minio-site1, minio-site2)
    - pgBackRest archiving enabled on the primary (PGBACKREST_ARCHIVE_ENABLED=true)
    - fastdb-wal buckets created in both MinIO instances
    - pgBackRest stanza created
    - elasticc2_test_data/ directory present (used by snana_fits_maintables_loaded_module)

Run with:
    pytest tests/test_wal_archive.py
"""

import os
import time
import urllib3

import pytest
from minio import Minio

from db import DB

# ---------------------------------------------------------------------------
# Configuration — override via environment variables if needed
# ---------------------------------------------------------------------------

MINIO_SITE1_ENDPOINT = os.environ.get("FASTDB_TEST_MINIO_SITE1_ENDPOINT", "minio-site1:9000")
MINIO_SITE2_ENDPOINT = os.environ.get("FASTDB_TEST_MINIO_SITE2_ENDPOINT", "minio-site2:9000")
MINIO_ACCESS_KEY = os.environ.get("FASTDB_TEST_MINIO_ACCESS_KEY", "minioadmin")
MINIO_SECRET_KEY = os.environ.get("FASTDB_TEST_MINIO_SECRET_KEY", "minioadmin")

S3_BUCKET = "fastdb-wal"
# pgBackRest repo paths inside the bucket (must match pgbackrest.conf)
REPO1_PREFIX = "repo1/archive/fastdb/"
REPO2_PREFIX = "repo2/archive/fastdb/"

# Path to the CA cert generated by init-certs (for TLS to MinIO)
CA_CERT_PATH = os.environ.get(
    "FASTDB_TEST_CA_CERT",
    os.path.join(os.path.dirname(__file__), "..", "certs", "ca.crt"),
)

# How long to wait for WAL archiving (seconds).
# The SNANA load is heavier (~52k forced sources), so allow extra time.
WAL_ARCHIVE_TIMEOUT = int(os.environ.get("FASTDB_TEST_WAL_TIMEOUT", "90"))
WAL_POLL_INTERVAL = 2


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_minio_client(endpoint: str):
    """Return a Minio client for the given endpoint.

    Uses the self-signed CA cert from init-certs if available,
    otherwise disables TLS verification.
    """
    if os.path.exists(CA_CERT_PATH):
        http_client = urllib3.PoolManager(
            cert_reqs="CERT_REQUIRED",
            ca_certs=CA_CERT_PATH,
        )
    else:
        http_client = urllib3.PoolManager(
            cert_reqs="CERT_NONE",
        )

    return Minio(
        endpoint,
        access_key=MINIO_ACCESS_KEY,
        secret_key=MINIO_SECRET_KEY,
        secure=True,
        http_client=http_client,
    )


def _list_wal_files(client: Minio, prefix: str):
    """List all object names under *prefix* in the WAL bucket.

    Returns a flat list of object names.  Returns an empty list
    if nothing exists under the prefix yet.
    """
    if not client.bucket_exists(S3_BUCKET):
        pytest.fail(
            f"Bucket '{S3_BUCKET}' does not exist at {client._base_url.host}. "
            "Create it before running integration tests."
        )

    return [obj.object_name for obj in client.list_objects(S3_BUCKET, prefix=prefix, recursive=True)]


def _force_wal_switch():
    """Force PostgreSQL to complete and archive the current WAL segment.

    pg_switch_wal() closes the current segment so pgBackRest's
    archive_command fires immediately rather than waiting for the
    segment to fill its full 16 MB.
    """
    with DB() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT pg_switch_wal();")
        conn.commit()


def _archiving_is_enabled():
    """Check that archive_mode is on and archive_command is set."""
    with DB() as conn:
        cursor = conn.cursor()
        cursor.execute("SHOW archive_mode;")
        mode = cursor.fetchone()[0]
        cursor.execute("SHOW archive_command;")
        command = cursor.fetchone()[0]
    return mode == "on" and bool(command.strip())


def _wait_for_new_wal(mc_site1, mc_site2, baseline_site1, baseline_site2):
    """Poll both MinIO stores until new WAL files appear or timeout.

    Returns (new_in_site1, new_in_site2) — sets of new object names.
    """
    deadline = time.time() + WAL_ARCHIVE_TIMEOUT
    new_in_site1: set[str] = set()
    new_in_site2: set[str] = set()

    while time.time() < deadline:
        current_site1 = set(_list_wal_files(mc_site1, REPO1_PREFIX))
        current_site2 = set(_list_wal_files(mc_site2, REPO2_PREFIX))

        new_in_site1 = current_site1 - baseline_site1
        new_in_site2 = current_site2 - baseline_site2

        if new_in_site1 and new_in_site2:
            break

        time.sleep(WAL_POLL_INTERVAL)

    return new_in_site1, new_in_site2


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def mc_site1():
    """Minio client for site 1."""
    return _get_minio_client(MINIO_SITE1_ENDPOINT)


@pytest.fixture(scope="module")
def mc_site2():
    """Minio client for site 2."""
    return _get_minio_client(MINIO_SITE2_ENDPOINT)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestWALArchiving:
    """Verify that WAL archiving via pgBackRest works end-to-end.

    Uses the snana_fits_maintables_loaded_module fixture which loads
    real ELAsTiCC2 FITS data through FITSLoader with 5 parallel
    processes, producing ~54k rows across diaobject, diasource,
    diaforcedsource, host_galaxy, and root_diaobject.  This exercises
    the production ingest path and generates enough WAL to meaningfully
    test archiving.
    """

    # -- Pre-conditions ----------------------------------------------------

    def test_archiving_is_enabled(self):
        """archive_mode must be 'on' and archive_command must be set."""
        assert _archiving_is_enabled(), (
            "WAL archiving is not enabled on the primary. "
            "Ensure PGBACKREST_ARCHIVE_ENABLED=true is set."
        )

    def test_minio_site1_reachable(self, mc_site1):
        """MinIO site 1 must be reachable and the WAL bucket must exist."""
        assert mc_site1.bucket_exists(S3_BUCKET), (
            f"Bucket '{S3_BUCKET}' not found on minio-site1"
        )

    def test_minio_site2_reachable(self, mc_site2):
        """MinIO site 2 must be reachable and the WAL bucket must exist."""
        assert mc_site2.bucket_exists(S3_BUCKET), (
            f"Bucket '{S3_BUCKET}' not found on minio-site2"
        )

    # -- Core archiving test -----------------------------------------------

    def test_wal_archived_after_snana_load(
        self, snana_fits_maintables_loaded_module, mc_site1, mc_site2
    ):
        """Load ELAsTiCC2 FITS data, switch WAL, confirm segments in both stores.

        snana_fits_maintables_loaded_module (from conftest.py) uses
        FITSLoader to bulk-load real SNANA FITS files, producing:
          - 346 DiaObjects
          - 1,862 DiaSources
          - 52,172 DiaForcedSources
          - 356 host galaxies
          - 346 RootDiaObjects

        The fixture has already completed the load by the time pytest
        hands it to us.  We force a WAL segment switch and poll both
        MinIO buckets for newly archived segments.

        Steps:
            1. Record the current set of archived WAL files (baseline).
            2. Verify the fixture loaded the expected row counts.
            3. Call pg_switch_wal() to force segment completion.
            4. Poll both MinIO buckets until new WAL files appear (or timeout).
        """
        # 1. Baseline — WAL files already in each store.
        baseline_site1 = set(_list_wal_files(mc_site1, REPO1_PREFIX))
        baseline_site2 = set(_list_wal_files(mc_site2, REPO2_PREFIX))

        # 2. The fixture yields (nobj, nsrc, nfrc, nhost).
        nobj, nsrc, nfrc, nhost = snana_fits_maintables_loaded_module
        assert nobj == 346, f"Expected 346 DiaObjects, got {nobj}"
        assert nsrc == 1862, f"Expected 1862 DiaSources, got {nsrc}"
        assert nfrc == 52172, f"Expected 52172 DiaForcedSources, got {nfrc}"
        assert nhost == 0, f"Expected 0 host galaxies, got {nhost}"

        # 3. Force WAL segment switch so archive_command fires.
        _force_wal_switch()

        # 4. Poll both stores for new WAL files.
        new_in_site1, new_in_site2 = _wait_for_new_wal(
            mc_site1, mc_site2, baseline_site1, baseline_site2
        )

        assert new_in_site1, (
            f"No new WAL files appeared in MinIO site 1 (repo1) within "
            f"{WAL_ARCHIVE_TIMEOUT}s. Baseline had {len(baseline_site1)} files."
        )
        assert new_in_site2, (
            f"No new WAL files appeared in MinIO site 2 (repo2) within "
            f"{WAL_ARCHIVE_TIMEOUT}s. Baseline had {len(baseline_site2)} files."
        )

        # Log what was archived (visible with pytest -v -s)
        print(f"\n  SNANA load: {nobj} objects, {nsrc} sources, "
              f"{nfrc} forced sources, {nhost} hosts")
        print(f"  Site 1: {len(new_in_site1)} new WAL file(s) archived")
        print(f"  Site 2: {len(new_in_site2)} new WAL file(s) archived")
        for key in sorted(new_in_site1)[:5]:
            print(f"    repo1: {key}")
        for key in sorted(new_in_site2)[:5]:
            print(f"    repo2: {key}")

    # -- Repeated archiving (catches credential/lock issues) ---------------

    def test_wal_archived_after_second_switch(self, mc_site1, mc_site2):
        """A second pg_switch_wal must also archive successfully.

        This catches edge cases where the archive_command works once but
        fails on subsequent invocations (e.g., credential expiry, stale
        pgBackRest lock files, repo connectivity issues).
        """
        baseline_site1 = set(_list_wal_files(mc_site1, REPO1_PREFIX))
        baseline_site2 = set(_list_wal_files(mc_site2, REPO2_PREFIX))

        # A CHECKPOINT generates some WAL; the switch archives it.
        with DB() as conn:
            cursor = conn.cursor()
            cursor.execute("CHECKPOINT;")
            conn.commit()

        _force_wal_switch()

        new_in_site1, new_in_site2 = _wait_for_new_wal(
            mc_site1, mc_site2, baseline_site1, baseline_site2
        )

        assert new_in_site1, "Second WAL switch did not archive to site 1"
        assert new_in_site2, "Second WAL switch did not archive to site 2"
