apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "fastdb.namespace" . }}
  labels:
    {{- include "fastdb.labels" . | nindent 4 }}
    {{- with .Values.global.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
