{{- if .Values.global.registryCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.registryCredentials.secretName }}
  namespace: {{ include "fastdb.namespace" . }}
  labels:
    {{- include "fastdb.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.global.registryCredentials.server .Values.global.registryCredentials.username .Values.global.registryCredentials.password (printf "%s:%s" .Values.global.registryCredentials.username .Values.global.registryCredentials.password | b64enc) | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ include "fastdb.namespace" . }}
  labels:
    {{- include "fastdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  pgpasswd: {{ .Values.secrets.postgres.password | quote }}
  postgres_ro_password: {{ .Values.secrets.postgres.roPassword | quote }}
  replicator_password: {{ .Values.secrets.postgres.replicatorPassword | quote }}
  secretkey: {{ .Values.secrets.secretKey | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: {{ include "fastdb.namespace" . }}
  labels:
    {{- include "fastdb.labels" . | nindent 4 }}
data:
  MONGODB_HOST: {{ .Values.mongodb.config.host | quote }}
  MONGODB_DBNAME: {{ .Values.mongodb.config.database | quote }}
  MONGODB_COLLECTION: {{ .Values.mongodb.config.collection | quote }}
  MONGODB_ADMIN_USER: {{ .Values.secrets.mongodb.adminUser | quote }}
  MONGODB_ADMIN_PASSWD: {{ .Values.secrets.mongodb.adminPassword | quote }}
  MONGODB_ALERT_READER_USER: {{ .Values.secrets.mongodb.readerUser | quote }}
  MONGODB_ALERT_READER_PASSWD: {{ .Values.secrets.mongodb.readerPassword | quote }}
  MONGODB_ALERT_WRITER_USER: {{ .Values.secrets.mongodb.writerUser | quote }}
  MONGODB_ALERT_WRITER_PASSWD: {{ .Values.secrets.mongodb.writerPassword | quote }}
