apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: desc-fastdb-postgres-pvc-20260319a
  namespace: desc-fastdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2048Gi
  storageClassName: nfs-client-vast
  volumeMode: Filesystem
