apiVersion: batch/v1
kind: CronJob
metadata:
  name: sourceimporter
  namespace: desc-fastdb
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            field.cattle.io/ports: '[[]]'
            nersc.gov/collab_uids: "99895"
            nersc.gov/gid: "95089"
            nersc.gov/gids: 60152,57177,95089,96414,99895
            nersc.gov/roles: user
            nersc.gov/uid: "95089"
            nersc.gov/username: raknop
          creationTimestamp: null
        spec:
          containers:
          - command: [ '/bin/bash' ]
            args:
              - -c
              - "python /fastdb/services/source_importer.py -o realtime_0 -p realtime_0 -s realtime_0 -f realtime_0 -v -c fink_alerts > /logs/sourceimporter_`date -Isec`.log 2>&1"
            workingDir: /brokerconsumer
            env:
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_DBNAME
              value: brokeralert
            - name: MONGODB_COLLECTION
              value: alerts
            - name: MONGODB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: mongodb_admin
                  name: secrets
                  optional: false
            - name: MONGODB_ADMIN_PASSWD
              valueFrom:
                secretKeyRef:
                  key: mongodb_admin_passwd
                  name: secrets
                  optional: false
            - name: MONGODB_ALERT_WRITER_USER
              valueFrom:
                secretKeyRef:
                  key: mongodb_alert_writer
                  name: secrets
                  optional: false
            - name: MONGODB_ALERT_WRITER_PASSWD
              valueFrom:
                secretKeyRef:
                  key: mongodb_alert_writer_password
                  name: secrets
                  optional: false
            - name: MONGODB_ALERT_READER_USER
              valueFrom:
                secretKeyRef:
                  key: mongodb_alert_reader
                  name: secrets
                  optional: false
            - name: MONGODB_ALERT_READER_PASSWD
              valueFrom:
                secretKeyRef:
                  key: mongodb_alert_reader_password
                  name: secrets
                  optional: false
            image: registry.nersc.gov/m1727/raknop/fastdb-shell:20260225b
            imagePullPolicy: IfNotPresent
            name: sourceimporter
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_BIND_SERVICE
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 95089
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
              - mountPath: /secrets
                name: secrets
              - mountPath: /fastdb
                name: fastdb-install
              - mountPath: /logs
                name: fastdb-brokerconsumer-logs
            workingDir: /fastdb
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 57177
          terminationGracePeriodSeconds: 30
          imagePullSecrets:
            - name: registry-nersc
          volumes:
          - name: secrets
            secret:
              defaultMode: 292
              optional: false
              secretName: secrets
          - hostPath:
              path: /global/cfs/cdirs/desc-td/SOFTWARE/fastdb_deployment/production/install
              type: Directory
            name: fastdb-install
          - hostPath:
              path: /global/cfs/cdirs/desc-td/SOFTWARE/fastdb_deployment/production/brokerconsumer_logs
              type: Directory
            name: fastdb-brokerconsumer-logs
  schedule: "22 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
