apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastdb-rknop-dev-kafka-data-20250409
  namespace: fastdb-rknop-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
