apiVersion: v1
data:
  pgpasswd: ZnJhZ2lsZQ==
  postgres_ro_password: bHlicnQ0dmt5dW51
  secretkey: NmQ4NnVyanVyYWE1
  mongodb_admin: bW9uZ29kYl9hZG1pbg==
  mongodb_admin_passwd: ZmdoaTI2NW1pMWI1
  mongodb_alert_reader: bW9uZ29kYl9hbGVydF9yZWFkZXI=
  mongodb_alert_reader_password: zrap03jdnu1a
  mongodb_alert_writer: bW9uZ29kYl9hbGVydF93cml0ZXI=
  mongodb_alert_writer_password: NWl1MTRndjcwZnp4
kind: Secret
metadata:
  name: secrets
  namespace: fastdb-rknop-dev
type: Opaque
