---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: fastdb-rknop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-fastdb-rknop-dev-webserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "99895"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 60152,57177,95089,96414,99895
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-fastdb-rknop-dev-webserver
    spec:
      affinity: {}
      containers:
      - image: registry.nersc.gov/m1727/raknop/fastdb-webap:rknop-dev
        imagePullPolicy: Always
        name: webserver
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: secrets
        - mountPath: /fastdb
          name: fastdb-install
        - mountPath: /query_results
          name: fastdb-query-results
        - mountPath: /sessions
          name: fastdb-sessions
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 57177
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: secrets
        secret:
          defaultMode: 292
          optional: false
          secretName: secrets
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/fastdb_deployment/rknop_dev/install
          type: Directory
        name: fastdb-install
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/fastdb_deployment/rknop_dev/query_results
          type: Directory
        name: fastdb-query-results
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/fastdb_deployment/rknop_dev/sessions
          type: Directory
        name: fastdb-sessions
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: fastdb-rknop-dev
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-fastdb-rknop-dev-webserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-ingress
  namespace: fastdb-rknop-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-fastdb-rknop-dev-webserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nersc.gov/clustername: production
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  name: webserver
  namespace: fastdb-rknop-dev
spec:
  rules:
  - host: webserver.fastdb-rknop-dev.production.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: webserver-ingress
            port:
              number: 8080
        pathType: ImplementationSpecific
  # - host: fastdb-rknop-dev.lbl.gov
  #   http:
  #     paths:
  #     - backend:
  #         service:
  #           name: webserver-ingress
  #           port:
  #             number: 8080
  #       pathType: ImplementationSpecific
  # tls:
  # - hosts:
  #   - fastdb-rknop-dev.lbl.gov
  #   secretName: fastdb-cert
---
