apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastdb-resspect-test-kafka-data-20250502
  namespace: fastdb-resspect-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
