---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: fastdb-resspect-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-fastdb-resspect-test-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "99895"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 60152,57177,95089,96414,99895
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-fastdb-resspect-test-mongodb
    spec:
      initContainers:
      - name: mongodb-volume-mount-hack
        image: busybox
        command:
        - /bin/sh
        args:
        - -c
        - chown 999:999 /data
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: mongodb-datadir
      containers:
      - name: mongodb
        image: registry.nersc.gov/m1727/raknop/fastdb-mongodb:resspect-test
        env:
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_DBNAME
          value: brokeralert
        - name: MONGODB_COLLECTION
          value: alerts
        - name: MONGODB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: mongodb_admin
              name: secrets
              optional: false
        - name: MONGODB_ADMIN_PASSWD
          valueFrom:
            secretKeyRef:
              key: mongodb_admin_passwd
              name: secrets
              optional: false
        - name: MONGODB_ALERT_WRITER_USER
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_writer
              name: secrets
              optional: false
        - name: MONGODB_ALERT_WRITER_PASSWD
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_writer_password
              name: secrets
              optional: false
        - name: MONGODB_ALERT_READER_USER
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_reader
              name: secrets
              optional: false
        - name: MONGODB_ALERT_READER_PASSWD
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_reader_password
              name: secrets
              optional: false
        imagePullPolicy: Always
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /mongodb-data
          name: mongodb-datadir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: mongodb-datadir
        persistentVolumeClaim:
          claimName: fastdb-resspect-test-mongodb-pvc-20250502
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: fastdb-resspect-test
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-fastdb-resspect-test-mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
