#!/usr/bin/env bash
# Prepare and install FASTDB on a single-node Kubernetes cluster.
set -euo pipefail

####################
##### Preamble
####################

# Locate the repository and require one environment-specific Helm values file.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RELEASE_NAME="fastdb"
SECRETS_FILE="$REPO_ROOT/helm/fastdb/values-arbutus-secrets.yaml"
EXTERNAL_URL="${FASTDB_EXTERNAL_URL:-http://localhost:30080/}"
REGISTRY_PULL_SECRET="fastdb-registry"

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <values-file>" >&2
  echo "Example: $0 ../fastdb/values-arbutus.yaml" >&2
  exit 1
fi

VALUES_FILE="$1"
if [[ ! -f "$VALUES_FILE" ]]; then
  echo "Error: values file not found: $VALUES_FILE" >&2
  exit 1
fi
VALUES_FILE="$(cd "$(dirname "$VALUES_FILE")" && pwd)/$(basename "$VALUES_FILE")"

# Read one simple scalar from the controlled single-node values files without
# requiring a separate YAML command-line tool.
# We run makeinstall before Helm, so extract the image metadata that Docker
# Compose needs from the values file.
read_values_scalar() {
  local key="$1"
  local line
  local value

  line="$(grep -m1 -E "^[[:space:]]*${key}:" "$VALUES_FILE" || true)"
  value="${line#*:}"
  value="${value%%#*}"
  value="$(printf '%s' "$value" | sed \
    -e 's/^[[:space:]]*//' \
    -e 's/[[:space:]]*$//' \
    -e 's/^"//' -e 's/"$//' \
    -e "s/^'//" -e "s/'$//")"
  if [[ -z "$line" || -z "$value" ]]; then
    echo "Error: could not read '$key' from $VALUES_FILE." >&2
    exit 1
  fi
  printf '%s\n' "$value"
}

NAMESPACE="$(read_values_scalar namespace)"
export DOCKER_ARCHIVE="$(read_values_scalar imageRegistry)"
export DOCKER_VERSION="$(read_values_scalar imageTag)"
SHELL_IMAGE="$DOCKER_ARCHIVE/fastdb-shell:$DOCKER_VERSION"
REGISTRY_HOST="${DOCKER_ARCHIVE%%/*}"

# Require a normal user and every command used by the installer.
if [[ $EUID -eq 0 ]]; then
  echo "Error: run this script as your normal user, not with sudo." >&2
  exit 1
fi
for command_name in curl docker git helm kubectl openssl; do
  command -v "$command_name" >/dev/null || {
    echo "Error: $command_name is required." >&2
    exit 1
  }
done

# Confirm that this user can access Docker and the Kubernetes cluster.
docker info >/dev/null 2>&1 || {
  echo "Error: cannot access Docker as $(id -un)." >&2
  echo "Ensure this user has Docker access, then log out and back in." >&2
  exit 1
}
kubectl get node >/dev/null || {
  echo "Error: the Kubernetes cluster is not accessible through kubectl." >&2
  exit 1
}

# Discover the node address used by the broker-consumer proxy.
NODE_IP="$(
  kubectl get nodes \
    --output=jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}'
)"
if [[ -z "$NODE_IP" ]]; then
  echo "Error: could not determine the Kubernetes node's internal IP address." >&2
  exit 1
fi

# Initialize source dependencies and verify writable host-mounted directories.
echo "Initializing Git submodules..."
git -C "$REPO_ROOT" submodule update --init --recursive
mkdir -p "$REPO_ROOT/install" "$REPO_ROOT/db"
for directory in "$REPO_ROOT/install" "$REPO_ROOT/db"; do
  if [[ ! -w "$directory" || ! -x "$directory" ]]; then
    echo "Error: $(id -un) cannot write to $directory." >&2
    echo "Fix its ownership, then rerun this script:" >&2
    echo "  sudo chown -R $(id -u):$(id -g) '$directory'" >&2
    exit 1
  fi
done

# Warn before deployment if the VM's root disk is running low on space.
AVAILABLE_KB="$(df -Pk / | awk 'NR == 2 { print $4 }')"
if (( AVAILABLE_KB < 10 * 1024 * 1024 )); then
  echo "Warning: less than 10 GiB is available on the root filesystem." >&2
fi

echo "Values file: $VALUES_FILE"
echo "Kubernetes namespace: $NAMESPACE"
echo "FASTDB images: $DOCKER_ARCHIVE/fastdb-*:$DOCKER_VERSION"
echo "Kubernetes node address: $NODE_IP"

####################
##### End of preamble
####################

# Generate deployment credentials once and reuse them on later upgrades.
if [[ ! -f "$SECRETS_FILE" ]]; then
  echo "Creating persistent development secrets in $SECRETS_FILE..."
  umask 077
  cat >"$SECRETS_FILE" <<EOF
# Generated by install-singlenode-fastdb.sh. Do not commit this file.
secrets:
  postgres:
    password: "$(openssl rand -hex 24)"
    roPassword: "$(openssl rand -hex 24)"
    replicatorPassword: "$(openssl rand -hex 24)"
  secretKey: "$(openssl rand -hex 32)"
  mongodb:
    adminUser: admin
    adminPassword: "$(openssl rand -hex 24)"
    readerUser: alertreader
    readerPassword: "$(openssl rand -hex 24)"
    writerUser: alertwriter
    writerPassword: "$(openssl rand -hex 24)"
EOF
fi

cd "$REPO_ROOT"

# The temporary makeinstall container needs the configured shell image before
# Helm runs. Explain this separate Docker requirement before offering a pull.
if ! docker image inspect "$SHELL_IMAGE" >/dev/null 2>&1; then
  echo
  echo "The FASTDB shell image is not available in Docker:"
  echo "  $SHELL_IMAGE"
  echo
  echo "This image is needed before Helm runs because the temporary"
  echo "makeinstall container uses it to prepare FASTDB/install/ from"
  echo "the current checkout."
  echo

  if [[ "$DOCKER_ARCHIVE" == "fastdb.local" ]]; then
    echo "fastdb.local is a local image label, not a remote registry."
    echo "Build and load that image tag first:"
    echo "  $REPO_ROOT/helm/scripts/build-local-images.sh '$DOCKER_ARCHIVE' '$DOCKER_VERSION'"
    exit 1
  fi

  echo "The configured registry is:"
  echo "  $DOCKER_ARCHIVE"
  echo
  read -r -p "Attempt to pull the shell image now? [y/N] " pull_reply
  case "$pull_reply" in
    y|Y|yes|YES|Yes)
      docker pull "$SHELL_IMAGE"
      ;;
    ""|n|N|no|NO|No)
      echo "Installation cancelled before Helm was run."
      exit 0
      ;;
    *)
      echo "Error: please answer y or n." >&2
      exit 1
      ;;
  esac
fi

# For any remote registry, verify every deployment image before running Helm.
# If the values file requests the standard pull secret, copy the existing
# Docker login into the namespace so Kubernetes can authenticate to it.
if [[ "$DOCKER_ARCHIVE" != "fastdb.local" ]]; then
  echo "Checking prebuilt registry images..."
  for repository in \
    fastdb-postgres \
    fastdb-mongodb \
    fastdb-shell \
    fastdb-webap \
    fastdb-query-runner
  do
    image_name="$DOCKER_ARCHIVE/$repository:$DOCKER_VERSION"
    echo "  Checking $image_name"
    if ! docker manifest inspect "$image_name" >/dev/null 2>&1; then
      echo "Error: cannot access $image_name." >&2
      echo "Run 'docker login $REGISTRY_HOST', verify the repository and tag, and rerun." >&2
      exit 1
    fi
  done

  if grep -Eq "^[[:space:]]*-[[:space:]]*name:[[:space:]]*$REGISTRY_PULL_SECRET([[:space:]]|$)" "$VALUES_FILE"; then
    docker_config_file="${DOCKER_CONFIG:-$HOME/.docker}/config.json"
    if [[ ! -f "$docker_config_file" ]]; then
      echo "Error: Docker credentials not found at $docker_config_file." >&2
      echo "Run 'docker login $REGISTRY_HOST' and rerun this script." >&2
      exit 1
    fi

    kubectl create namespace "$NAMESPACE" \
      --dry-run=client \
      --output=yaml |
      kubectl apply --filename=- >/dev/null
    kubectl create secret generic "$REGISTRY_PULL_SECRET" \
      --namespace "$NAMESPACE" \
      --type=kubernetes.io/dockerconfigjson \
      --from-file=.dockerconfigjson="$docker_config_file" \
      --dry-run=client \
      --output=yaml |
      kubectl apply --filename=- >/dev/null
  fi
fi

# Use the configured shell image to copy and configure the current checkout in
# the host's install/ directory. Kubernetes later mounts it at /fastdb.
echo "Building FASTDB install/ for $EXTERNAL_URL..."
USERID="$(id -u)" GROUPID="$(id -g)" \
docker compose run --rm --entrypoint "" makeinstall /bin/bash -ec "
  touch aclocal.m4 configure
  find . -name Makefile.am -exec touch {} \\;
  find . -name Makefile.in -exec touch {} \\;
  ./configure \\
    --with-installdir=/fastdb \\
    --with-smtp-server=mailhog \\
    --with-smtp-port=1025 \\
    --with-external-url=$EXTERNAL_URL
  make install
"

# Recreate one-shot Jobs because Kubernetes does not allow Helm to update their
# pod templates in place, then install or upgrade the remaining resources.
echo "Installing FASTDB with Helm..."
kubectl delete job createdb ingestion-processing-version \
  --namespace "$NAMESPACE" \
  --ignore-not-found

if ! helm upgrade --install "$RELEASE_NAME" "$REPO_ROOT/helm/fastdb" \
  --namespace "$NAMESPACE" \
  --create-namespace \
  --values "$VALUES_FILE" \
  --values "$SECRETS_FILE" \
  --set-string "volumes.hostPaths.install=$REPO_ROOT/install" \
  --set-string "volumes.hostPaths.db=$REPO_ROOT/db" \
  --set-string "ingestion.brokerConsumer.dockerHostIp=$NODE_IP" \
  --wait \
  --wait-for-jobs \
  --timeout 10m; then
  echo "Helm installation failed. Current status:" >&2
  kubectl get pods --namespace "$NAMESPACE" >&2 || true
  kubectl logs --namespace "$NAMESPACE" job/createdb >&2 || true
  exit 1
fi

# Restart long-running Python processes so they load code from the refreshed
# host-mounted install/ directory.
echo "Restarting services that load the host-mounted FASTDB code..."
for deployment_name in webap queryrunner shell; do
  kubectl rollout restart "deployment/$deployment_name" --namespace "$NAMESPACE"
  kubectl rollout status "deployment/$deployment_name" \
    --namespace "$NAMESPACE" \
    --timeout=180s
done

# Verify the web application, then display final workload and storage status.
echo "Checking FASTDB WebAP..."
curl --fail --silent --show-error \
  --retry 12 \
  --retry-all-errors \
  --retry-delay 5 \
  "http://127.0.0.1:30080/" >/dev/null

echo
kubectl get pods --namespace "$NAMESPACE"
kubectl get pvc --namespace "$NAMESPACE"
df -h /
echo
echo "FASTDB is ready inside the VM at http://localhost:30080"
echo "MailHog is ready inside the VM at http://localhost:30025"
